// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_service.proto

package io.reactivesw.catalog.grpc;

public final class CatalogService {
  private CatalogService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025catalog_service.proto\022$io.reactivesw.c" +
      "atalog.infrastructure\032\032catalog_data_mess" +
      "age.proto\032\025catalog_message.proto2\373\001\n\017Cat" +
      "egoryService\022p\n\rgetCategories\022+.io.react" +
      "ivesw.catalog.infrastructure.Empty\0322.io." +
      "reactivesw.catalog.infrastructure.Catego" +
      "ryList\022v\n\017getCategoryById\022/.io.reactives" +
      "w.catalog.infrastructure.LongValue\0322.io." +
      "reactivesw.catalog.infrastructure.GrpcCa" +
      "tegory2\213\002\n\016ProductService\022\200\001\n\025getProduct",
      "sByCategory\022/.io.reactivesw.catalog.infr" +
      "astructure.LongValue\0326.io.reactivesw.cat" +
      "alog.infrastructure.ProductBriefList\022v\n\020" +
      "getProductDetial\022/.io.reactivesw.catalog" +
      ".infrastructure.LongValue\0321.io.reactives" +
      "w.catalog.infrastructure.GrpcProductB\036\n\032" +
      "io.reactivesw.catalog.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.reactivesw.catalog.grpc.CatalogDataMessage.getDescriptor(),
          io.reactivesw.catalog.grpc.CatalogMessage.getDescriptor(),
        }, assigner);
    io.reactivesw.catalog.grpc.CatalogDataMessage.getDescriptor();
    io.reactivesw.catalog.grpc.CatalogMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
