// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_data_message.proto

package io.reactivesw.catalog.grpc;

public final class CatalogDataMessage {
  private CatalogDataMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catalog_infrastructure_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_reactivesw_catalog_infrastructure_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catalog_infrastructure_LongValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_reactivesw_catalog_infrastructure_LongValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catalog_infrastructure_IntValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_reactivesw_catalog_infrastructure_IntValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032catalog_data_message.proto\022$io.reactiv" +
      "esw.catalog.infrastructure\"\007\n\005Empty\"\032\n\tL" +
      "ongValue\022\r\n\005value\030\001 \001(\003\"\031\n\010IntValue\022\r\n\005v" +
      "alue\030\001 \001(\005B!\n\032io.reactivesw.catalog.grpc" +
      "P\001\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_reactivesw_catalog_infrastructure_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_reactivesw_catalog_infrastructure_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_reactivesw_catalog_infrastructure_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_io_reactivesw_catalog_infrastructure_LongValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_reactivesw_catalog_infrastructure_LongValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_reactivesw_catalog_infrastructure_LongValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_io_reactivesw_catalog_infrastructure_IntValue_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_reactivesw_catalog_infrastructure_IntValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_reactivesw_catalog_infrastructure_IntValue_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
