// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_sku_service.proto

package io.reactivesw.catalog.grpc;

public final class CatalogSkuService {
  private CatalogSkuService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031catalog_sku_service.proto\022$io.reactive" +
      "sw.catalog.infrastructure\032\031catalog_sku_m" +
      "essage.proto\032\032catalog_data_message.proto" +
      "2\216\003\n\nSkuService\022t\n\021querySkuInventory\022/.i" +
      "o.reactivesw.catalog.infrastructure.Long" +
      "Value\032..io.reactivesw.catalog.infrastruc" +
      "ture.IntValue\022\202\001\n\031querySkuSimpleInformat" +
      "ion\022/.io.reactivesw.catalog.infrastructu" +
      "re.LongValue\0324.io.reactivesw.catalog.inf" +
      "rastructure.SkuInformation\022\204\001\n\027querySkuI",
      "nformationList\022/.io.reactivesw.catalog.i" +
      "nfrastructure.SkuIdList\0328.io.reactivesw." +
      "catalog.infrastructure.SkuInformationLis" +
      "tB\036\n\032io.reactivesw.catalog.grpcP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.reactivesw.catalog.grpc.CatalogSkuMessage.getDescriptor(),
          io.reactivesw.catalog.grpc.CatalogDataMessage.getDescriptor(),
        }, assigner);
    io.reactivesw.catalog.grpc.CatalogSkuMessage.getDescriptor();
    io.reactivesw.catalog.grpc.CatalogDataMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
