// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_data_message.proto

package io.reactivesw.catalog.grpc;

public interface IntValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catalog.infrastructure.IntValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The int32 value.
   * </pre>
   *
   * <code>optional int32 value = 1;</code>
   */
  int getValue();
}
