// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_data_message.proto

package io.reactivesw.catalog.grpc;

public interface LongValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catalog.infrastructure.LongValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The int64 value.
   * </pre>
   *
   * <code>optional int64 value = 1;</code>
   */
  long getValue();
}
